### ISSUE TITLE
如何添加我的生词本里面的"只看今日添加"

### ISSUE THREAD

**Issue by sbbbsbbb** [yihong0618/shanbay_remember#11]
我尝试过修改
  `/wordsapp/user_material_books/${materialbookId}/learning/words/today_learning_items?ipp=10&page=${page}&type_of=${wordsType}`;
修改成
`/wordscollection/learning/words/today_learning_items?ipp=10&page=1&type_of=NEW`
workflows 是可以正常运行起来的,但是bot里面没有输出

**Comment by yihong0618** [comment]
不太确定这个，我稍后看一下，你搞定了，PR welcome

**Comment by BeautyyuYanli** [comment]
你是想只接收新单词的推送吗？删除这一行即可：
https://github.com/yihong0618/shanbay_remember/blob/bd95af50e3945b8dc10de3c28437c9fc3f1c248d/shanbay.js#L141
