### ISSUE TITLE
Error for FFmpeg

### ISSUE THREAD

**Issue by BeautyyuYanli** [yihong0618/shanbay_remember#15]
The audio downloaded from Shanbay may be with different fomat (e.g. aac) and cannot be concated.

https://github.com/BeautyyuYanli/shanbay_remember/actions/runs/4783776450/jobs/8504678091

A workaround is drafted in https://github.com/BeautyyuYanli/shanbay_remember/commit/f5f3782f23573e899cd1c8789dd8094f3d3166f8 , which 
- Run the download audio function in a single thread to avoid too much connection at the same time.
- Convert audio files to mp3 before concat.

**Comment by yihong0618** [comment]
nice

**Comment by yihong0618** [comment]
can you open a PR with this change?
