### ISSUE TITLE
secrets都设置好了，接下来再怎么做啊？

### ISSUE THREAD

**Issue by Sherwin6180** [yihong0618/shanbay_remember#8]

**Comment by yihong0618** [comment]
如果是fork的，得去actions点下手动触发。
别忘了得先背下今日的单词。

**Comment by Sherwin6180** [comment]
> 如果是fork的，得去actions点下手动触发。
> 
> 别忘了得先背下今日的单词。

请问该如何激活？我的actions下显示“This scheduled workflow is disabled because scheduled workflows are disabled by default in forks.”

**Comment by yihong0618** [comment]
> > 如果是fork的，得去actions点下手动触发。
> > 别忘了得先背下今日的单词。
> 
> 请问该如何激活？我的actions下显示“This scheduled workflow is disabled because scheduled workflows are disabled by default in forks.”

啊，两种方案。1 改点东西 push
2. clone一份变成自己项目

**Comment by Sherwin6180** [comment]
> > > 如果是fork的，得去actions点下手动触发。
> 
> > > 别忘了得先背下今日的单词。
> 
> > 
> 
> > 请问该如何激活？我的actions下显示“This scheduled workflow is disabled because scheduled workflows are disabled by default in forks.”
> 
> 
> 
> 啊，两种方案。1 改点东西 push
> 
> 2. clone一份变成自己项目

好像成功了，我也创建了一个telegram机器人，chatid和token也设置好了，请问在机器人上怎么操作呢，比如设置命令？

**Comment by yihong0618** [comment]
这个你需要查bot的文档～
